local cfg = {}

cfg.market_types = {
	["24/7"] = {
		_config = {blipid = 59, blipcolor = 11},
		["head_bag"] = {200, "General"},
		["mouthgag"] = {500, "General"},
		-- ["dices"] = {100, "General"},
		-- ["rope"] = {500, "General"},
		["zipbagcoca"] = {500, "General"},
		["jar"] = {500, "General"},
		["water"] = {10, "Bauturi"},
		["cola"] = {20, "Bauturi"},
		["redbull"] = {30, "Bauturi"},
		["lipton"] = {15, "Bauturi"},
		["fanta"] = {10, "Bauturi"},
		["cafea"] = {15, "Bauturi"},
		["lapte"] = {10, "Bauturi"},
		["milkshake"] = {20, "Bauturi"},
		["pepene_rosu"] = {5, "Mancare"},
		["gogoasa_ciocolata"] = {15, "Gustari"},
		["gogoasa_capsuni"] = {12, "Gustari"},
		["chipsuri_lays"] = {10, "Gustari"},
		["sandvis"] = {15, "Mancare"},
		["cookie"] = {10, "Gustari"},
		["hotdog"] = {25, "Mancare"},
		-- ['elastic'] = {100, "General"},
		["briosa"] = {10, "Gustari"},
		["pizza"] = {20, "Mancare"},
		['repairkit'] = {3500, "General"},
		-- ['rope'] = {200, 'General'},
		['lockpick'] = {1000, 'General'},
		['rope'] = {1500, 'General'},
	},
	["Fast Food"] = {
		_config = {blipid = 628, blipcolor = 36},
		["water"] = {10, "Bauturi"},
		["cola"] = {20, "Bauturi"},
		["redbull"] = {30, "Bauturi"},
		["lipton"] = {15, "Bauturi"},
		["fanta"] = {10, "Bauturi"},
		["cafea"] = {15, "Bauturi"},
		["lapte"] = {10, "Bauturi"},
		["milkshake"] = {20, "Bauturi"},
		["shaorma"] = {30, "Mancare"},
		["pleskavita"] = {35, "Mancare"},
		["tacos"] = {20, "Mancare"},
		["burger"] = {30, "Mancare"},
		["burrito"] = {30, "Mancare"},
		["cookie"] = {10, "Gustari"},
		["hotdog"] = {25, "Mancare"},
		-- ['elastic'] = {100, "General"},
		["pizza"] = {20, "Mancare"},
	},
	["Club"] = {
		_config = {blipid = 93, blipcolor = 8, iconColor = {254, 122, 195, 200}},
		["water"] = {10, "General"},
		["cola"] = {25, "General"},
		["lipton"] = {20, "General"},
		["fanta"] = {15, "General"},
		["redbull"] = {45, "General"},
		["vodka"] = {150, "Sticle"},
		["milkshake"] = {30, "General"},
		["bere"] = {20, "General"},
		["bloody_mary"] = {55, "Pahare"},
		-- ["trabuc"] = {1000, "General"},
		["pina-colada"] = {50, "Pahare"},
		["martini"] = {45, "Pahare"},
		["sticla_sampanie"] = {5000, "Sticle"},
		["sticla_vin"] = {1000, "Sticle"},
		["sticla_tequila"] = {700, "Sticle"},
		["sticla_whiskey"] = {950, "Sticle"},
		["pahar_sampanie"] = {200, "Pahare"},
		["pahar_vin"] = {75, "Pahare"},
		["shot_tequila"] = {40, "Pahare"},
		["pahar_whiskey"] = {55, "Pahare"},
	},
	["Electronice"] = {
		_config = {blipid = 459, blipcolor = 3, iconColor = {93, 182, 229, 200}},
		["phone"] = {500, "General"},
		["radio"] = {350, "General"},
		["usbstick"] = {100, "General"},
		["laptop_h"] = {100, "General"},
	},
	["Genti"] = {
		_config = {blipid = 676, blipcolor = 13, iconColor = {211, 209, 231, 200}},
		["ghiozdanMare"] = {100000, "General"},
		["ghiozdanMediu"] = {50000, "General"},
		["ghiozdanMic"] = {25000, "General"},
	},
	["Mafia Market"] = {
		_config = {fType = "Mafie"},
		["body_armor"] = {5500, "Echipament"},
		["head_bag"] = {100, "Diverse"},
		["mouthgag"] = {100, "Diverse"},
		["bandage"] = {550, "Prim-Ajutor"},
		["adrenaline"] = {1000, "Prim-Ajutor"},
		["medkit"] = {15000, "Prim-Ajutor"},
		-- ['rope'] = {100, 'Diverse'},
		-- ["vehlockpick"] = 10000
	},
	["Farmacie"] = {
		_config = {blipid=61, blipcolor=75},
		["bandage"] = {1100, "Prim-Ajutor"},
		["paracetamol"] = {500, "Pastile"},
		["adrenaline"] = {2000, "Prim-Ajutor"},
	},
	["Pescarie"] = {
		_config = {blipid=728, blipcolor=3, iconColor = {0, 175, 255, 255}},
		['undita_3'] = {25000, "Undite"},
		['undita_2'] = {10000, "Undite"},
		['undita_1'] = {5000, "Undite"},
		["momeala"] = {150, "Momeala"},
	},
}

return cfg