Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Couches"] = {
    { ["object"] = "Couches", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Old Flowered Couch" },
    { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "3 Seat Chair" },
    { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Old 1 Seat Couch" },
    { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Old 3 Seat Couch" },
    { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Old Striped Couch" },
    { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Old 1 Seat Couch Yellow" },
    { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["name"] = "Corner Sofa" },
    { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["name"] = "Corner Sofa 2" },
    { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Sofa 1" },
    { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Sofa 2" },
    { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Sofa 3" },
    { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "Sofa 4" },
    { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Sofa 5" },
    { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Sofa 6" },
    { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Sofa 7" },
    { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Sofa 8" },
    { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Sofa 9" },
    { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Sofa 10" },
    { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Sofa 11" },
    { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "foot stool 1" },
    { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "foot stool 2" },
    { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 2000, ["name"] = "Canapea Alba-Rosie" },
    { ["object"] = "sum_mp_h_yacht_sofa_01", ["price"] = 2500, ["name"] = "Canapea Yacht" },
    { ["object"] = "v_ilev_m_sofa", ["price"] = 1000, ["name"] = "Canapea Alba" },
    { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 1000, ["name"] = "Fotoliu Negru" },
    { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 1000, ["name"] = "Fotoliu Galben" },
    { ["object"] = "apa_mp_h_stn_chairarm_23", ["price"] = 1000, ["name"] = "Fotoliu Visiniu" },
    { ["object"] = "apa_mp_h_stn_chairstrip_05", ["price"] = 1000, ["name"] = "Fotoliu Alb" },
    { ["object"] = "apa_mp_h_stn_chairstrip_04", ["price"] = 1000, ["name"] = "Fotoliu Rosu" },
    { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["name"] = "Fotoliu Yacht" },
    { ["object"] = "prop_t_sofa_02", ["price"] = 1000, ["name"] = "Canapea Alba Mica" },
    { ["object"] = "prop_couch_01", ["price"] = 1000, ["name"] = "Canapea Bej Maro" },
    { ["object"] = "prop_couch_lg_07", ["price"] = 1000, ["name"] = "Canapea Alba Portocaliu" },
    { ["object"] = "prop_couch_sm_07", ["price"] = 1000, ["name"] = "Fotoliu Alb 3" },
    { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 1000, ["name"] = "Canapea Albastra" },
    { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 1000, ["name"] = "Canapea Albastra 2" },
    { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 1000, ["name"] = "Canapea Alba 2" },
    { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 1000, ["name"] = "Canapea Gri" },
    { ["object"] = "hei_heist_stn_sofa2seat_02", ["price"] = 1000, ["name"] = "Canapea Rotunda" },

  },

  ["Chairs"] = {
    { ["object"] = "Chairs", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "High Chair" },
    { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Chair" },
    { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Chair" },
    { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "High Chair" },
    { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Dine Chair 1" },
    { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Dine Chair 2" },
    { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Dine Chair 3" },
    { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Chair" },
    { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Stool" },
    { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "High Chair" },
    { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Arm Chair" },
    { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Dining Chair" },
    { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Stool" },
    { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "MB Chair" },
    { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Arm Chair" },
    { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Dine Chair" },
    { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Study Chair" },
    { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Frame Chair" },
    { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Chair" },
    { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Office Chair" },
    { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Stool" },
    { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Stool Leather" },
    { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Stool Scuz" },
    { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Desk Chair" },
    { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Easy Chair" },
    { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Whicker Chair" },
    { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Direct Chair 1" },
    { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Direct Chair 2" },
    { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Yacht Seat 1" },
    { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Yacht Seat 2" },
    { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Yacht Seat 3" },
    { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Yacht Seat 4" },
    { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "White Chair" },
    { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Chair" },
    { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "TA Stool" },
    { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Office Chair" },
    { ["object"] = "prop_off_chair_01", ["price"] = 700, ["name"] = "Scaun Birou" },
    { ["object"] = "v_ret_gc_chair03", ["price"] = 800, ["name"] = "Scaun Birou Piele" },
    { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 700, ["name"] = "Fotoliu Ortopedic" },
    { ["object"] = "v_16_high_lng_armchairs", ["price"] = 1300, ["name"] = "Set Fotolii" },
    { ["object"] = "bkr_prop_clubhouse_armchair_01a", ["price"] = 800, ["name"] = "Fotoliu Negru" },
    { ["object"] = "v_res_mp_stripchair", ["price"] = 800, ["name"] = "Fotoliu Verde" },
    { ["object"] = "apa_mp_h_stn_chairstrip_02", ["price"] = 900, ["name"] = "Fotoliu Rosu" },
    { ["object"] = "xm_prop_x17_avengerchair", ["price"] = 1500, ["name"] = "Scaun Gaming" },
    { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 350, ["name"] = "Scaun Bucatarie Alb" },
    { ["object"] = "prop_off_chair_01", ["price"] = 350, ["name"] = "Scaun Birou 1" },
    { ["object"] = "ex_prop_offchair_exec_03", ["price"] = 350, ["name"] = "Scaun Birou 2" },
    { ["object"] = "prop_sol_chair", ["price"] = 350, ["name"] = "Scaun Birou 3" },
    { ["object"] = "apa_mp_h_stn_chairarm_03", ["price"] = 350, ["name"] = "Scaun Albastru" },
    { ["object"] = "bkr_prop_biker_barstool_01", ["price"] = 350, ["name"] = "Scaun Bar Alb" },
    { ["object"] = "bkr_prop_biker_barstool_02", ["price"] = 350, ["name"] = "Scaun Bar Alb 2" },
  },

  ["Beds"] = {
    { ["object"] = "Beds", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "D Bed" },  
    { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "L Bed" }, 
    { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "MB Bed" }, 
    { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "MD Bed" }, 
    { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Mason Bed" },  
    { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "T Bed" }, 
    { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "T Bed 2" }, 
    { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "TT Bed" },
    { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 700, ["name"] = "Double Bed" },  
    { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 700, ["name"] = "Double Bed 2" },
    { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 700, ["name"] = "Double Bed 3" },
    { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "Bed with table" },
    { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 500, ["name"] = "Single bed" },
    { ["object"] = "apa_mp_h_yacht_bed_02", ["price"] = 1000, ["name"] = "Pat 3 Persoane" },
  },

  ["General #1"] = {
    { ["object"] = "1", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Bean Bag 1" },
    { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "White Vase" },
    { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Padded Wall" },
    { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Item" },
    { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Whips" },
    { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Mags" },
    { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Mags Open" },
    { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Mag Tidy" },
    { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Yoga Mat 1" },
    { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Yoga Mat 2" },
    { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Aftershave" },
    { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Flowers" },
    { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
    { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Laundry Basket" },
    { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "Pouf" },
    { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Sculpture" },
    { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Mag Rack" },
    { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Jewel Box" },
    { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Bin" },
    { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Ornate Bowl" },
    { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Bronze Vase" },
    { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Chalk Board" },
    { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Dresser" },
    { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
    { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Ashtray" },
    { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Candle" },
    { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Candle Large" },
    { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Scales" },
    { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Bed Pillow" },
    { ["object"] = "vw_prop_vw_wallart_03a", ["price"] = 300, ["name"] = "Tablou 1" },
    { ["object"] = "vw_prop_vw_wallart_06a", ["price"] = 300, ["name"] = "Tablou 2" },
    { ["object"] = "vw_prop_vw_wallart_132a", ["price"] = 300, ["name"] = "Tablou 3" },
    { ["object"] = "vw_prop_vw_wallart_30a", ["price"] = 300, ["name"] = "Tablou 4" },
    { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 300, ["name"] = "Wall Art 1" },
    { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 300, ["name"] = "Wall Art 2" },
    { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Wall Art 3" },
    { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 300, ["name"] = "Wall Art 4" },
    { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 300, ["name"] = "Wall Art 5" },
    { ["object"] = "apa_mp_h_acc_artwalll_01", ["price"] = 200, ["name"] = "Pictura Rosie" },
    { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 200, ["name"] = "Pictura Portocalie" },
    { ["object"] = "apa_mp_h_acc_artwalll_03", ["price"] = 200, ["name"] = "Pictura Albastra" },
    { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 200, ["name"] = "Pictura Plaja" },
    { ["object"] = "apa_mp_h_acc_artwallm_03", ["price"] = 200, ["name"] = "Pictura Colorata" },
    { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 200, ["name"] = "Pictura Rosie 2" },
    { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 300, ["name"] = "Rug 1" },
    { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 300, ["name"] = "Rug 2" },
    { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 300, ["name"] = "Rug 3" },
    { ["object"] = "apa_mp_h_acc_rugwoolm_01", ["price"] = 500, ["name"] = "Covor Rosu" },
    { ["object"] = "apa_mp_h_acc_rugwoolm_02", ["price"] = 500, ["name"] = "Covor Verde" },
  },

  ["General #2"] = {
    { ["object"] = "2", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_disp_cabinet_01", ["price"] = 3000, ["name"] = "Vitrina Bonguri" },
    { ["object"] = "prop_cash_case_01", ["price"] = 3000, ["name"] = "Servieta Cu Bani" },
    { ["object"] = "hei_prop_hei_drug_case", ["price"] = 4000, ["name"] = "Servieta cu Cocaina" },
    { ["object"] = "ch_prop_ch_security_case_01a", ["price"] = 6000, ["name"] = "Servieta cu Diamante" },
    { ["object"] = "vw_prop_vw_watch_case_01b", ["price"] = 4000, ["name"] = "Vitrina cu Ceasuri" },
    { ["object"] = "apa_mp_h_08_pants5", ["price"] = 100, ["name"] = "Lenjerie Intima Leopard" },
    { ["object"] = "apa_mp_h_01_pants2", ["price"] = 150, ["name"] = "Lenjerie Intima Rosie" },
    { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "A4 Pile" },
    { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 oz" },
    { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Beer" },
    { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Aviators" },
    { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Detail" },
    { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Beers" },
    { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculars" },
    { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Blox Spray" },
    { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongos" },
    { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong" },
    { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Boombox" },
    { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Bowl Crisps" },
    { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Candy" },
    { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Carrier bag" },
    { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ceramic Jug" },
    { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Cigar Pack 1" },
    { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Cigar Pack 2" },
    { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Beer Box 2" },
    { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Binder" },
    { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Cup" },
    { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
    { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flute" },
    { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Duffel Bag" },
    { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
    { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Case" },
    { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Film Reel" },
    { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Blind" },
    { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Bag" },
    { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Ironing Board" },
    { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
    { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Kettle" },
    { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Crate" },
    { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Petrol Can" },
    { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Sack" },
    { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Script Bottle" },
    { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Script Bottle 2" },
    { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
    { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey Bottle" },
    { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong" },
    { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Peanuts" },
    { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Tumbler" },
    { ["object"] = "apa_mp_h_acc_bottle_01", ["price"] = 100, ["name"] = "Sticla Decorativa" },
    { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 100, ["name"] = "Masca Decorativa" },
    { ["object"] = "bkr_prop_bkr_cashpile_05", ["price"] = 100, ["name"] = "Gramada de Bani" },
  },

  ["General #3"] = {
    { ["object"] = "3", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "p_wine_glass_s", ["price"] = 150, ["name"] = "Pahar Vin" },
    { ["object"] = "prop_wine_bot_01", ["price"] = 400, ["name"] = "Sticla Vin" },
    { ["object"] = "apa_p_apa_champ_flute_s", ["price"] = 100, ["name"] = "Pahar Vin Spumant" },
    { ["object"] = "apa_mp_h_acc_fruitbowl_01", ["price"] = 150, ["name"] = "Platou Fructe" },
    { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 100, ["name"] = "Bol Fructe" },
    { ["object"] = "v_24_lnb_mesh_books", ["price"] = 100, ["name"] = "Carti" },
    { ["object"] = "ch_chint02_books", ["price"] = 100, ["name"] = "Carti 2" },
    { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "CSR Bin" },
    { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Basket" },
    { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "GC Bag 1" },
    { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "GC Bag 2" },
    { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "GC Bin" },
    { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Cash Register" },
    { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "GC Chair 01" },
    { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "GC Chair 02" },
    { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Clock" },
    { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
    { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Prod 2" },
    { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
    { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
    { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
    { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
    { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
    { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
    { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Fridge" },
    { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Bag 1" },
    { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bag 2" },
    { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Book 1" },
    { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Book 2" },
    { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Book 3" },
    { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Book 4" },
    { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Cam" },
    { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "First Aid" },
    { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Hero" },
    { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Mag 1" },
    { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Mag 2" },
    { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Skull" },
    { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitar" },
    { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Handbag" },
    { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Case" },
    { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Big Bag" },
    { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Bonesaw" },
    { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertilizer" },
    { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Shopping Bag" },
    { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Vial" },
    { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Ragdoll" }, 
    { ["object"] = "prop_suitcase_01d", ["price"] = 100, ["name"] = "Valiza Neagra" }, 
  },

  ["General #4"] = {
    { ["object"] = "4", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Dummy" },
    { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Egg Clock" },
    { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
    { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
    { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
    { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Feed Sack" },
    { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Floor Duster" },
    { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Fruit Basket" },
    { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Duster" },
    { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Grapes" },
    { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Hotel Clock" },
    { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Idol Case" },
    { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Jewels" },
    { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Display Tray" },
    { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
    { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Handbag" },
    { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
    { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
    { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
    { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 1" },
    { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 2" },
    { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
    { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Rasberry Clean" },
    { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Paper Bag" },
    { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Shopping Bags" },
    { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Shopping Bags 2" },
    { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Yoga Mat 1" },
    { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Yoga Mat 2" },
    { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Yoga Mat 3" },
    { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Sax" },
    { ["object"] = "prop_barbell_01", ["price"] = 100, ["name"] = "Gantera" },
    { ["object"] = "prop_barbell_100kg", ["price"] = 100, ["name"] = "Bara cu Greutati" },
    { ["object"] = "apa_p_apdlc_treadmill_s", ["price"] = 100, ["name"] = "Banda de Alergat" },
    { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "SOCCER Ball" },
    { ["object"] = "prop_game_clock_02", ["price"] = 100, ["name"] = "Ceas 2" },
    { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Watch 1" },
    { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Watch 2" },
    { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Watch 3" },
    { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Watch 4" },
    { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Watch 5" },
    { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Watch 6" },
  },

  ["Small"] = {
    { ["object"] = "Small", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Fig Cat" },
    { ["object"] = "p_cs_joint_02", ["price"] = 200, ["name"] = "Joint" },
    { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Fig Clown" },
    { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Fig Auth" },
    { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Fig Female" },
    { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Fig Flamenco" },
    { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Fig Girl" },
    { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Fig Girl Clown" },
    { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
    { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Fig Pillar" },
    { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Teapot" },
    { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Sculpture 1" },
    { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Sculpture 2" },
    { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Sculpture 3" },
    { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Sculpture 4" },
    { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skateboard" },
    { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Sketchpad" },
    { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Tissues" },
    { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Basket" },
    { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Bin" },
    { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Cushion 1" },
    { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Cushion 2" },
    { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Cushion 3" },
    { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Cushion 4" },
    { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Cushion 5" },
    { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Cushion 6" },
    { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
    { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Sideboard" },
    { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Idol 1" },
    { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["name"] = "Cuffs" },
    { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Good vibes" },
    { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Good vibes 2" },
    { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Good vibes 3" },
    { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "Good vibes 4" },
    { ["object"] = "v_res_d_lube", ["price"] = 100, ["name"] = "Lube" },
    { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Desk tray" },
    { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "File box" },
    { ["object"] = "p_cs_lighter_01", ["price"] = 50, ["name"] = "Bricheta" },
    { ["object"] = "apa_mp_h_acc_scent_sticks_01", ["price"] = 100, ["name"] = "Betisoare Parfumate" },
  },

  ["Storage"] = {
    { ["object"] = "Storage", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "ba_wardrobe", ["price"] = 1000, ["name"] = "Garderoba" },
    { ["object"] = "prop_cabinet_01b", ["price"] = 1500, ["name"] = "Sifonier Alb" },
    { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 1300, ["name"] = "Sifonier Mov" },
    { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 1300, ["name"] = "Sifonier Maro" },
    { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 1000, ["name"] = "Sifonier Modern-Alb" },
    { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 1000, ["name"] = "Sifonier Modern-Crem" },
    { ["object"] = "apa_mp_h_str_sideboards_01", ["price"] = 1000, ["name"] = "Sifonier Modern-Gri" },
    { ["object"] = "apa_mp_h_01_sideboard", ["price"] = 900, ["name"] = "Sifonier Lemn-Maro" },
    { ["object"] = "apa_mp_h_06_livingsideboard", ["price"] = 900, ["name"] = "Sifonier Lemn" },
    { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Cabinet Large" },
    { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Dressing Table" },
    { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Side Unit" },
    { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Side Unit" },
    { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Side Unit" },
    { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Bed Unit" },
    { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Tv Unit" },
    { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Dresser Unit" },
    { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Bottoman Unit" },
    { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Console Unit" },
    { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Cupboard Unit" },
    { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Chest Unit" },
    { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Mason Unit" },
    { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Armoire Unit" },
    { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Side Unit" },
    { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Desk Unit" },
    { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Side Unit" },
    { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Side Unit 2" },
    { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Book Unit" },
    { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Box Unit" },
    { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Storage Unit" },
    { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Wardrobe Unit" },
    { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Wood Unit" },
    { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Bean Bag 1" },
    { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Mil Crate 1" },
    { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Mil Crate 2" },
    { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Safe" },
    { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 1100, ["name"] = "Rafturi" },
    { ["object"] = "apa_mp_h_str_sideboardl_13", ["price"] = 1100, ["name"] = "SideBoard 5" },
    { ["object"] = "v_16_high_bed_mesh_unit", ["price"] = 1100, ["name"] = "Biblioteca Alba" },

  },

  ["Electronics"] = {
    { ["object"] = "Electronics", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Old Fridge" },
    { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Speaker" },
    { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Speaker Dock" },
    { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Bedside Clock" },
    { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Phone" },
    { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Tower Fan" },
    { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fan" },
    { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Bigscreen" },
    { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
    { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
    { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
    { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Laptop" },
    { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },
    { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "Flatscreen TV" },
    { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "TV set 1" },
    { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "TV set 2" },
    { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1000, ["name"] = "TV set 3" },
    { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Jukebox" },
    { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Floor fan" },
    { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "Computer Keyboard" },
    { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Coffeemachine" },
    { ["object"] = "hei_heist_str_avunitl_03", ["price"] = 1500, ["name"] = "Home Cinema" },
    { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 2000, ["name"] = "Home Cinema 2" },
    { ["object"] = "prop_tv_flat_03", ["price"] = 500, ["name"] = "Monitor" },
    { ["object"] = "prop_controller_01", ["price"] = 300, ["name"] = "Controller" },
    { ["object"] = "prop_console_01", ["price"] = 1000, ["name"] = "Consola" },
    { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 1500, ["name"] = "TV + Mobila" },
    { ["object"] = "prop_laptop_lester2", ["price"] = 1500, ["name"] = "Laptop 2" },
    { ["object"] = "prop_dyn_pc_02", ["price"] = 1500, ["name"] = "Unitate PC" },
    { ["object"] = "prop_tv_flat_01", ["price"] = 1500, ["name"] = "Televizor Plat" },
    { ["object"] = "v_res_mousemat", ["price"] = 1500, ["name"] = "Mouse Pad + Mouse" },
    { ["object"] = "apa_mp_h_str_avunitl_01_b", ["price"] = 1500, ["name"] = "TV + Mobila Cafeniu" },
  },


  ["Lighting"] = {
    { ["object"] = "Lighting", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Desk Corp Lamp" },
    { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Desk Lamp" },
    { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Lamp AA" },
    { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Lamp 1" },
    { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Floor Lamp" },
    { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lamp 2" },
    { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Table Lamp" },
    { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Table Lamp 2" },
    { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Bed Lamp" },
    { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Plant Tongue Lamp" },
    { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Table Lamp 3" },
    { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Lamp Stand" },
    { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Lamp Stand 2" },
    { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Table Lamp 4" },
    { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Light Fan" },
    { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Tall Lamp" },
    { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Wall Light" },
    { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "GC Lamp" },
    { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Flickering Light" },
    { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Side Wall Light" },
    { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 600, ["name"] = "Lampa Mica" },
    { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 500, ["name"] = "Lampa Dormitor" },
    { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 400, ["name"] = "Lampa Futuristica" },
    { ["object"] = "apa_mp_h_floorlamp_c", ["price"] = 400, ["name"] = "Lampa Futuristica Neagra" },
    { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["name"] = "Lumanare Verde" },
    { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["name"] = "Lumanare Rosie" },
    { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["name"] = "Lumanare Albastra Aprinsa" },
    { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["name"] = "Lumanare Rosie Aprinsa" },
    { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 300, ["name"] = "Set 3 Lumanari Albastre" },
    { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 200, ["name"] = "Lumanari Albe" },
    { ["object"] = "apa_mp_h_lampbulb_multiple_a", ["price"] = 600, ["name"] = "Becuri Multe" },
  },


  ["Tables"] = {
    { ["object"] = "Tables", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 1" },
    { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Round Table" },
    { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Small Side Table" },
    { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Table A" },
    { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Table B" },
    { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Table C" },
    { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Dining Table" },
    { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 2" },
    { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Low Table" },
    { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Bed Table" },
    { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Desk" },
    { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Side Table" },
    { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Console Table" },
    { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Dining Table 2" },
    { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Console H Table" },
    { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Stool?" },
    { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Sideboard Table" },
    { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Table 2" },
    { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Tv Table" },
    { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Tv Table Tall" },
    { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Med Coffee Table" },
    { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Med Desk" },
    { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Yacht Table 1" },
    { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Yacht Table 2" },
    { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Yacht Table 3" },
    { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "CSR Table" },
    { ["object"] = "hei_heist_din_table_06", ["price"] = 100, ["name"] = "Dinner table w chairs" },
    { ["object"] = "prop_t_coffe_table", ["price"] = 300, ["name"] = "Masuta neagra de cafea" },
    { ["object"] = "apa_mp_h_tab_coffee_08", ["price"] = 600, ["name"] = "Masuta Cafea Alba" },
    { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 1000, ["name"] = "Masa Sticla" },
    { ["object"] = "ex_mp_h_din_table_06", ["price"] = 1000, ["name"] = "Masa Alba" },
    { ["object"] = "ex_mp_h_din_table_01", ["price"] = 1300, ["name"] = "Masa Sticla-Silver" },
    { ["object"] = "xm_prop_lab_desk_02", ["price"] = 1300, ["name"] = "Birou Negru" },
    { ["object"] = "prop_t_coffe_table_02", ["price"] = 1300, ["name"] = "Masuta de Cafea" },
    { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 1300, ["name"] = "Masa Sticla Inalta" },
    { ["object"] = "ex_mp_h_din_table_05", ["price"] = 1300, ["name"] = "Masa Maro" },
    { ["object"] = "hei_heist_tab_coffee_07", ["price"] = 1300, ["name"] = "Masa Mica Cafea" },
    { ["object"] = "h4_prop_casino_3cardpoker_01a", ["price"] = 1300, ["name"] = "Masa Poker" },

  },

  ["Plants"] = {
    { ["object"] = "Plants", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Plant Fib" },
    { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Plant Bomb" },    
    { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Plant Flowers" }, 
    { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Plant Chinese" }, 
    { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Plant Banana" }, 
    { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Plant Palm" },  
    { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Plant Palm 2" },  
    { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Plant Urn" },  
    { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Plant Rubber" }, 
    { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Plant" }, 
    { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Plant Tree" }, 
    { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planter" }, 
    { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flowers" },
    { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flowers 1" },
    { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flowers 2" },
    { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 100, ["name"] = "Flowers 3" },
    { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Flowers 4" },
    { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Christmas Tree" },
    { ["object"] = "prop_plant_int_03a", ["price"] = 300, ["name"] = "Planta in vaza" },
    { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 1000, ["name"] = "Ornament Trandafiri" },
    { ["object"] = "apa_mp_h_acc_vase_02", ["price"] = 300, ["name"] = "Vaza Rosie" },
    { ["object"] = "apa_mp_h_acc_vase_05", ["price"] = 300, ["name"] = "Vaza Gri" },
    { ["object"] = "vw_prop_casino_art_plant_05a", ["price"] = 300, ["name"] = "Planta 1" },
    { ["object"] = "vw_prop_casino_art_plant_04a", ["price"] = 300, ["name"] = "Planta 2" },
    { ["object"] = "vw_prop_flowers_vase_01a", ["price"] = 300, ["name"] = "Vaza cu Flori Albe" },
  },

  ["Kitchen"] = {
    { ["object"] = "Kitchen", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Washer 1" },
    { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Washer 2" },
    { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Washer 3" },
    { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Washing Basket" },
    { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Fridge 1" },
    { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Fridge 2" },
    { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Fridge 3" },
    { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Fridge 4" },
    { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Cooker" },
    { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microwave 1" },
    { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Microwave 2" },
    { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Wok" },
    { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Cake Plate" },
    { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Chopping Board" },
    { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Utensils" },
    { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pestle" },
    { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "PaperRoll 1" },
    { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "PaperRoll 2" },
    { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Pot 1" },
    { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Pot 2" },
    { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Pot 3" },
    { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Pot 4" },
    { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Pot 5" },
    { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Pot 6" },
    { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Pot 7" },
    { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Pot Rack" },
    { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Juicer" },
    { ["object"] = "prop_food_bs_bag_02", ["price"] = 150, ["name"] = "Punga Burger" },
    { ["object"] = "v_ret_247_popbot4", ["price"] = 150, ["name"] = "Sticla Cola" },
    { ["object"] = "v_ret_fh_pizza01", ["price"] = 150, ["name"] = "Cutie Pizza" },
    { ["object"] = "prop_cs_burger_01", ["price"] = 150, ["name"] = "Burger" },
    { ["object"] = "prop_bottle_cognac", ["price"] = 150, ["name"] = "Sticla Cognac" },
    { ["object"] = "prop_champ_cool", ["price"] = 150, ["name"] = "Sticla Sampanie" },
    { ["object"] = "prop_plonk_white", ["price"] = 150, ["name"] = "Sticla Vin Alb" },
    { ["object"] = "prop_wine_glass", ["price"] = 150, ["name"] = "Pahar Vin Alb" },
    { ["object"] = "spiritsrow", ["price"] = 150, ["name"] = "Mix Bauturi" },
    { ["object"] = "ba_prop_battle_champ_open_03", ["price"] = 150, ["name"] = "Sticla Sampanie 2" },
  },


  ["Bathroom"] = {
    { ["object"] = "Bathroom", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Toilet 1" },
    { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Toilet 2" },
    { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Toilet 3" },
    { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Sink 1" },
    { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Sink 2" },
    { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Sink 3" },
    { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Sink 4" },
    { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Soap Dispenser" },
    { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Shower Rack" },
    { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Hand Dryer 1" },
    { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Hand Dryer 2" },
    { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Towel Rail 1" },
    { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Towel Rail 2" },
    { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Towel 1" },
    { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Towel 2" },
    { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Towel 3" },
    { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Bath" },
    { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Sink" },
  },

  ["Medical"] = {
    { ["object"] = "Medical", ["price"] = 999, ["name"] = "X" },
    { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barrel" },
    { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Ape Crate" },
    { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Ape Crate Large" },
    { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Bed 1" },
    { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Bed 2" },
    { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Bed Table" },
    { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Bench 1" },
    { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Bench 2" },
    { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Bench Center" },
    { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Bench Set" },
    { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
    { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Bin" },
    { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrifuge" },
    { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Cooler" },
    { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
    { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Autopsy Table" },
    { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Bin" },
    { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Trolley" },
    { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Chem" },
    { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "BLM Table" },
    { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "File Box" },
    { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "File Cab" },
    { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Hose" },
    { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Large Cupboard" },
    { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Lightbox" },
    { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Medstool" },
    { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Minifridge" },
    { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Papertowels" },
    { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Photocopy" },
    { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "TV Stand" },
    { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Wall Unit" },
    { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Exam light" },
    { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Gas Tank" },
    { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Hazmat Scan" },
    { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Head Wall" },
    { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Seating" },
    { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Hosp Table" },
    { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Glove Box" },
    { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Wastebin" },
    { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Oscillator" },
    { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Health Pack" },
  }
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end

-- Possible Message: (SENT)
          -- switch( event.data.type ) {
          --   case "init":
          --     Init(event.data)
          --   break;
          --   case "display":
          --     SetAlpha(event.data.enabled?1:0)
          --   break;
          --   case "focus":
          --     Focus(event.data)
          --   break;
          --   case "openEdit":
          --     OpenEdit(event.data)
          --   break;
          --   case "setTransform":
          --     SetTransform(event.data)
          --   break;
          --   case "setAlpha":
          --     SetAlpha(event.data.alpha)
          --   break;
          --   case "close":
          --     Close()
          --   break;
          --   case "open":
          --     Open()
          --   break;
          --   case "cancel":
          --     Cancel()
          --   break;
          -- }

-- Init(Config)
        -- onOpen            = config.onOpen
        -- onClose           = config.onClose
        -- onCancel          = config.onCancel
        -- onSelect          = config.onSelect
        -- onPlace           = config.onPlace 
        -- onStartAim        = config.onStartAim
        -- onStopAim         = config.onStopAim
        -- onReposition      = config.onReposition
        -- onRepositionStart = config.onRepositionStart
        -- onTransform       = config.onTransform
        -- onEdit            = config.onEdit
        -- onRemove          = config.onRemove
        -- onExit            = config.onExit
        -- top               = config.top
        -- left              = config.left