RegisterNUICallback('search:citizen', function(data, callback)
    triggerCallback('searchCitizen', function(info)
        callback(info)
    end, data.query)
end)

RegisterNUICallback('search:caziere_citizen', function(data, callback)
    triggerCallback('searchCazier', function(info)
        callback(info)
    end, data.id)
end)

RegisterNUICallback('search:amenda_citizen', function(data, callback)
    triggerCallback('searchAmenda', function(info)
        callback(info)
    end, data.id)
end)

RegisterNUICallback("search:incidents_citizen", function(data, callback)
    triggerCallback('searchCitizenIncidents', function(info)
        callback(info)
    end, data.id)
end)

RegisterNUICallback('search:vehicles_citizen', function(data, callback)
    triggerCallback('searchCitizenVehicles', function(info)
        callback(info)
    end, data.id)
end)

RegisterNUICallback('update:citizen', function(data, callback)
    triggerCallback('updateCitizenDescription', function(info)
        callback(info)
    end, data)
end)

RegisterNUICallback('update:photo', function(data, callback)
    triggerCallback('updatePhoto', function(info)
        callback(info)
    end, data.id, data.url)
end)