RegisterNUICallback('suggested:players', function(data, callback)
    triggerCallback('searchSuggestedPlayers', function(info)
        callback(info)
    end, data.query)
end)

RegisterNUICallback('suggested:cops', function(data, callback)
    triggerCallback('searchSuggestedCops', function(info)
        callback(info)
    end, data.query)
end)

RegisterNUICallback('suggested:vehicles', function(data, callback)
    triggerCallback('searchSuggestedVehicles', function(info)
        callback(info)
    end, data.query)
end)

RegisterNUICallback('suggested:fines', function(data, callback)
    triggerCallback('searchSuggestedFines', function(info)
        callback(info)
    end, data.query)
end)

RegisterNUICallback('suggested:jail', function(data, callback)
    triggerCallback('searchSuggstedCharges', function(info)
        callback(info)
    end, data.query)
end)